### ISSUE TITLE
You can load the current source code?

### ISSUE THREAD

**Issue by Opensorcio** [Alcmidia/souweb#2]
Hello @Alcmidia , i am writing to you from Italy;

- I want to translate into italian your search engine :-) . I was wondering: you can upload the new current source codes in GitHub?.

Thanks from Italy.

**Comment by Alcmidia** [comment]
Hi @Opensorcio , nice to talk with you,

    This is the version, i use free time to work on this, next step i gone group result by domain.

    If you want translate on include to portuguese and italian will be great, in this case i wait you translate to change search engine.

    I don't know how to use git very well, do i need to do something to allow you to upload the files?

Thank You
Leandro Pileggi

**Comment by Opensorcio** [comment]
Thank you for your answer @Alcmidia ;

(i know little about github);

would you be able to contact me via email on github or facebook? (always if it's not a problem).

(if you can send me the files by email or facebook).

Thanks 1000 :+1:

**Comment by Opensorcio** [comment]
Error[s] (php 8.0):

![2021-07-29-17-02-127 0 0 1](https://user-images.githubusercontent.com/88116946/127527823-7a9f43c4-5280-44e6-aec9-05f44e111240.png)

**Comment by Alcmidia** [comment]
Hi @Opensorcio , 

    We can chat by email or whatsapp, send a contact from https://www.alcmidia.com.br/contato/

    About the error, i dont test on php8 but i think can be .htaccess file

Thanks

**Comment by Opensorcio** [comment]
Hello Alcmidia, I wrote you in the online form :-) ;

I am waiting for your news by email.

Gioele

**Comment by Alcmidia** [comment]
Hi Giole, 

   Ok i made a reply to you, se if you receive correctly (maybe in spam box)

Thanks

**Comment by Opensorcio** [comment]
Ok, I answered, no problem :-)
